# Generated by Django 3.1.7 on 2021-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_site', '0002_auto_20210322_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='inn',
            field=models.CharField(blank=True, default='000000000000', max_length=14, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=25, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone_number',
            field=models.CharField(blank=True, default='0312000000', max_length=12, verbose_name='Номер телефона'),
        ),
    ]
